FROM alpine:latest@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099

LABEL "org.opencontainers.image.source"="https://github.com/pagopa/example-bad-repo-packages"
LABEL "maintainer"="https://pagopa.it"
